function catalogNode(tag,text,className){const e=document.createElement(tag);if(text)e.textContent=text;if(className)e.className=className;return e}
function catalogLeaderImage(type,detail=false){const image=document.createElement("img");image.src=`./leader-${type.id}.webp`;image.alt=`${type.jp}の上司像：${type.theme}`;image.width=900;image.height=900;image.loading="lazy";image.decoding="async";image.className=detail?"leader-detail-image":"leader-card-image";return image;}
function renderCatalog(){
 const cards=document.getElementById('catalogCards'),details=document.getElementById('catalogDetails'),filters=document.getElementById('baseFilters');
 LEADERSHIP_BASES.forEach(base=>{const button=catalogNode('button',base.jp,'filter-chip');button.type='button';button.dataset.base=String(base.index);button.setAttribute('aria-pressed','false');filters.appendChild(button)});
 const labels=[['essence','このタイプの本質'],['success','なぜ成果を出せるのか'],['decision','意思決定の特徴'],['mobilize','人の動かし方'],['normal','平常時の特徴'],['pressure','プレッシャーが高まったとき'],['process','強みが過剰化するプロセス'],['derailer','最も気をつけたい落とし穴'],['environment','力を発揮しやすい環境'],['difficult','苦戦しやすい環境'],['growth','成長するとどう変わるか'],['withBoss','このタイプが上司だった場合'],['withReport','このタイプの部下を持った場合'],['cooperate','噛み合いやすい組み方'],['friction','衝突が起きやすいポイント'],['reason','衝突が起きる理由'],['partner','うまく組む方法']];
 LEADERSHIP_TYPES.forEach(type=>{
  const a=catalogNode('a',null,'catalog-card');a.href=`#${type.id}`;a.dataset.type=type.id;a.appendChild(catalogLeaderImage(type));const h=catalogNode('h2',type.jp);a.appendChild(h);a.appendChild(catalogNode('div',type.en,'catalog-en'));a.appendChild(catalogNode('p',type.bases.map(x=>x.jp).join(' × '),'note'));a.appendChild(catalogNode('p',type.theme));a.appendChild(catalogNode('span','詳しく読む →','catalog-go'));cards.appendChild(a);
  const article=catalogNode('article',null,'catalog-article hidden');article.id=type.id;
  const header=catalogNode('header',null,'type-detail-hero');header.appendChild(catalogNode('div','組み合わせリーダータイプ','eyebrow'));header.appendChild(catalogNode('h1',type.jp));header.appendChild(catalogNode('div',type.en,'type-english'));header.appendChild(catalogNode('p',type.bases.map(x=>x.jp).join(' × '),'type-bases'));header.appendChild(catalogNode('p',type.theme,'type-catch'));header.appendChild(catalogLeaderImage(type,true));header.appendChild(catalogNode("p","イラストは上司像のイメージです。年齢・性別・外見でタイプが決まるものではありません。","note leader-image-note"));article.appendChild(header);
  const note=catalogNode('p','このページは基本的なリーダー像の解説です。あなた自身の得点を説明するものではありません。同じタイプでも、支援行動や負荷時の反応は70問の個別結果によって変わります。以下の強み・落とし穴は、実際の場面で確かめる仮説です。','note lens-note');article.appendChild(note);
  const toc=catalogNode('details',null,'disclosure type-toc');toc.appendChild(catalogNode('summary','このタイプの目次'));const nav=catalogNode('nav',null,'disclosure-body');nav.setAttribute('aria-label',`${type.jp}の目次`);labels.forEach(([key,label])=>{const link=catalogNode('a',label);link.href=`#${type.id}--${key}`;nav.appendChild(link)});const around=catalogNode('a','周囲からどう見えるか');around.href=`#${type.id}--around`;nav.appendChild(around);toc.appendChild(nav);article.appendChild(toc);
  labels.forEach(([key,label],n)=>{const section=catalogNode('section',null,'catalog-section');section.id=`${type.id}--${key}`;section.appendChild(catalogNode('h2',label));section.appendChild(catalogNode('p',type[key]));article.appendChild(section);
   if(n===3){const people=catalogNode('section',null,'catalog-section');people.id=`${type.id}--around`;people.appendChild(catalogNode('h2','周囲からどう見えるか'));[['部下から','reports'],['同僚から','peers'],['上司から','bosses']].forEach(([label,k])=>{people.appendChild(catalogNode('h3',label));people.appendChild(catalogNode('p',type[k]))});article.appendChild(people)}
  });
  const related=catalogNode('nav',null,'related-types no-print');related.setAttribute('aria-label','関連するタイプ');related.appendChild(catalogNode('h2','説明に登場するタイプ'));const referenced=LEADERSHIP_TYPES.filter(t=>t.id!==type.id&&[type.cooperate,type.friction].some(x=>x.includes(t.jp)));referenced.forEach(t=>{const link=catalogNode('a',`${t.jp} →`,'button-link secondary');link.href=`#${t.id}`;related.appendChild(link)});article.appendChild(related);details.appendChild(article);
 });
 let selectedBase=null;
 const input=document.getElementById('typeSearch'),count=document.getElementById('catalogCount'),empty=document.getElementById('catalogEmpty');
 const normalize=s=>s.normalize('NFKC').toLocaleLowerCase('ja-JP');
 function filter(){const tokens=normalize(input.value).trim().split(/\s+/).filter(Boolean);let n=0;LEADERSHIP_TYPES.forEach(type=>{const text=normalize([type.jp,type.en,type.theme,...type.bases.map(x=>x.jp)].join(' '));const visible=(selectedBase===null||type.a===selectedBase||type.b===selectedBase)&&tokens.every(x=>text.includes(x));document.querySelector(`[data-type="${type.id}"]`).classList.toggle('hidden',!visible);if(visible)n++});count.textContent=`${n} / 28タイプ`;empty.classList.toggle('hidden',n!==0)}
 input.addEventListener('input',filter);
 filters.addEventListener('click',e=>{const button=e.target.closest('button[data-base]');if(!button)return;const value=Number(button.dataset.base);selectedBase=selectedBase===value?null:value;[...filters.querySelectorAll('button')].forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.base)===selectedBase)));filter()});
 document.getElementById('clearFilters').addEventListener('click',()=>{selectedBase=null;input.value='';[...filters.querySelectorAll('button')].forEach(b=>b.setAttribute('aria-pressed','false'));filter();input.focus()});
 function route(){let fragment;try{fragment=decodeURIComponent(location.hash.slice(1))}catch{fragment='invalid'}const id=fragment.split('--')[0],type=LEADERSHIP_TYPES.find(x=>x.id===id),detail=Boolean(type);document.getElementById('catalogOverview').classList.toggle('hidden',detail);document.getElementById('catalogDetailNav').classList.toggle('hidden',!detail);document.getElementById('catalogInvalid').classList.toggle('hidden',!fragment||fragment==='catalog'||detail);[...details.children].forEach(a=>a.classList.toggle('hidden',a.id!==type?.id));document.title=type?`${type.jp} | LEADERSHIP LENS`:'28タイプ リーダーシップ図鑑 | LEADERSHIP LENS';if(detail){const target=document.getElementById(fragment)||document.getElementById(type.id);target.scrollIntoView({behavior:'auto',block:'start'});const h=target.querySelector('h1,h2');if(h){h.tabIndex=-1;h.focus({preventScroll:true})}}else window.scrollTo(0,0)}
 window.addEventListener('hashchange',route);filter();route();
}
renderCatalog();

